#!/usr/bin/env bash

set -eo pipefail; [[ "$TRACE" ]] && set -x

main() {
	declare version="${1:-$GLIBC_VERSION}" prefix="${2:-$PREFIX_DIR}"

	: "${version:?}" "${prefix:?}"

	{
		wget -qO- "http://ftp.gnu.org/gnu/glibc/glibc-${version}.tar.gz" \
			| tar zxf -
		mkdir -p /glibc-build && cd /glibc-build
		"/glibc-${version}/configure" \
		    --host=x86_64-pc-linux-gnu \
			--with-headers="/usr/include" \
			--prefix="${prefix}" \
			--libdir="${prefix}/lib" \
			--libexecdir="${prefix}/lib" \
			--enable-multi-arch
		# patch the old rpc types
		sed -i -e 's/defined __APPLE_CC__ || defined __FreeBSD__/defined __APPLE_CC__ || defined __FreeBSD__ || defined(_GNU_SOURCE)/g' /glibc-${version}/sunrpc/rpc/types.h
		make && make install
		tar --hard-dereference -zcf "/glibc-bin-${version}.tgz" "${prefix}"
	} >&2

	[[ $STDOUT ]] && cat "/glibc-bin-${version}.tgz"
}

main "$@"
